-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 23:06:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema solidaireplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solidaireplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solidaireplus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `solidaireplus` ;

-- -----------------------------------------------------
-- Table `solidaireplus`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`user` (
  `cin` INT NOT NULL,
  `nom` VARCHAR(20) NULL DEFAULT NULL,
  `prenom` VARCHAR(20) NULL DEFAULT NULL,
  `numtelephone` INT NULL DEFAULT NULL,
  PRIMARY KEY (`cin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`admin` (
  `cinadmin` INT NOT NULL,
  PRIMARY KEY (`cinadmin`),
  INDEX `fk_admin_user1_idx` (`cinadmin` ASC) VISIBLE,
  CONSTRAINT `fk_admin_user1`
    FOREIGN KEY (`cinadmin`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`collecteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`collecteur` (
  `cincollecteur` INT NOT NULL,
  `collecteurcol` VARCHAR(45) NULL,
  PRIMARY KEY (`cincollecteur`),
  INDEX `fk_collecteur_user1_idx` (`cincollecteur` ASC) VISIBLE,
  CONSTRAINT `fk_collecteur_user1`
    FOREIGN KEY (`cincollecteur`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`affectation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`affectation` (
  `idaffectation` INT NOT NULL,
  `cindonneur` INT NULL DEFAULT NULL,
  `libellé` VARCHAR(20) NULL DEFAULT NULL,
  `cinhandicapé` INT NULL DEFAULT NULL,
  `cincollecteur` INT NOT NULL,
  PRIMARY KEY (`idaffectation`),
  INDEX `fk_affectation_collecteur1_idx` (`cincollecteur` ASC) VISIBLE,
  CONSTRAINT `fk_affectation_collecteur1`
    FOREIGN KEY (`cincollecteur`)
    REFERENCES `solidaireplus`.`collecteur` (`cincollecteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`handicapé`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`handicapé` (
  `cinhandicapé` INT NOT NULL,
  `adressehandicapé` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cinhandicapé`),
  INDEX `fk_handicapé_user1_idx` (`cinhandicapé` ASC) VISIBLE,
  CONSTRAINT `fk_handicapé_user1`
    FOREIGN KEY (`cinhandicapé`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`cartesoins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`cartesoins` (
  `idcarte` INT NOT NULL,
  PRIMARY KEY (`idcarte`),
  INDEX `fk_cartesoins_handicapé1_idx` (`idcarte` ASC) VISIBLE,
  CONSTRAINT `fk_cartesoins_handicapé1`
    FOREIGN KEY (`idcarte`)
    REFERENCES `solidaireplus`.`handicapé` (`cinhandicapé`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`catégorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`catégorie` (
  `idcatégorie` INT NOT NULL,
  `type` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idcatégorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`compte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`compte` (
  `idcompte` INT NOT NULL,
  `email` VARCHAR(20) NULL DEFAULT NULL,
  `motdepasse` VARCHAR(20) NULL DEFAULT NULL,
  `admin_cinadmin1` INT NOT NULL,
  INDEX `fk_compte_user1_idx` (`idcompte` ASC) VISIBLE,
  PRIMARY KEY (`idcompte`),
  INDEX `fk_compte_admin1_idx` (`admin_cinadmin1` ASC) VISIBLE,
  CONSTRAINT `fk_compte_user1`
    FOREIGN KEY (`idcompte`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compte_admin1`
    FOREIGN KEY (`admin_cinadmin1`)
    REFERENCES `solidaireplus`.`admin` (`cinadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`donneur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`donneur` (
  `cindonneur` INT NOT NULL,
  PRIMARY KEY (`cindonneur`),
  INDEX `fk_donneur_user1_idx` (`cindonneur` ASC) VISIBLE,
  CONSTRAINT `fk_donneur_user1`
    FOREIGN KEY (`cindonneur`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`demande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`demande` (
  `iddemande` INT NOT NULL,
  `datedemande` DATE NULL DEFAULT NULL,
  `cinhandicapé` INT NOT NULL,
  `cindonneur` INT NOT NULL,
  PRIMARY KEY (`iddemande`),
  INDEX `fk_demande_handicapé1_idx` (`cinhandicapé` ASC) VISIBLE,
  INDEX `fk_demande_donneur1_idx` (`cindonneur` ASC) VISIBLE,
  CONSTRAINT `fk_demande_handicapé1`
    FOREIGN KEY (`cinhandicapé`)
    REFERENCES `solidaireplus`.`handicapé` (`cinhandicapé`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_demande_donneur1`
    FOREIGN KEY (`cindonneur`)
    REFERENCES `solidaireplus`.`donneur` (`cindonneur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`don`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`don` (
  `donneur_cindonneur` INT NOT NULL,
  `libellé` VARCHAR(20) NOT NULL,
  `description` VARCHAR(20) NULL DEFAULT NULL,
  `quantite` INT NULL DEFAULT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  `idcatégorie` INT NOT NULL,
  PRIMARY KEY (`donneur_cindonneur`, `libellé`),
  INDEX `fk_don_catégorie1_idx` (`idcatégorie` ASC) VISIBLE,
  INDEX `fk_don_donneur1_idx` (`donneur_cindonneur` ASC) VISIBLE,
  CONSTRAINT `fk_don_catégorie1`
    FOREIGN KEY (`idcatégorie`)
    REFERENCES `solidaireplus`.`catégorie` (`idcatégorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_don_donneur1`
    FOREIGN KEY (`donneur_cindonneur`)
    REFERENCES `solidaireplus`.`donneur` (`cindonneur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`livraison`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`livraison` (
  `idlivraison` INT NOT NULL,
  `nomcollecteur` VARCHAR(20) NULL DEFAULT NULL,
  `libellé` VARCHAR(20) NULL DEFAULT NULL,
  `adressehandicapé` VARCHAR(20) NULL DEFAULT NULL,
  `confirmation` VARCHAR(20) NULL DEFAULT NULL,
  `datereception` DATE NULL DEFAULT NULL,
  `cincollecteur` INT NOT NULL,
  `admin_cinadmin1` INT NOT NULL,
  PRIMARY KEY (`idlivraison`),
  INDEX `fk_livraison_collecteur1_idx` (`cincollecteur` ASC) VISIBLE,
  INDEX `fk_livraison_admin1_idx` (`admin_cinadmin1` ASC) VISIBLE,
  CONSTRAINT `fk_livraison_collecteur1`
    FOREIGN KEY (`cincollecteur`)
    REFERENCES `solidaireplus`.`collecteur` (`cincollecteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livraison_admin1`
    FOREIGN KEY (`admin_cinadmin1`)
    REFERENCES `solidaireplus`.`admin` (`cinadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solidaireplus`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solidaireplus`.`profile` (
  `idprofile` INT NOT NULL,
  `email` VARCHAR(20) NULL DEFAULT NULL,
  `motdepasse` VARCHAR(20) NULL DEFAULT NULL,
  `role` VARCHAR(20) NULL DEFAULT NULL,
  INDEX `fk_profile_user1_idx` (`idprofile` ASC) VISIBLE,
  PRIMARY KEY (`idprofile`),
  CONSTRAINT `fk_profile_user1`
    FOREIGN KEY (`idprofile`)
    REFERENCES `solidaireplus`.`user` (`cin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
